export const SocialHandles = [
  {
    name: "Twitter",
    src: "/socials/x-icon.svg",
    link: "https://x.com/msxcodes",
  },
  {
    name: "LinkedIn",
    src: "/socials/linkedin-icon02.svg",
    link: "https://www.linkedin.com/in/msxcodes/",
  },
  {
    name: "Instagram",
    src: "/socials/insta-icon02.svg",
    link: "https://www.instagram.com/msxcodes",
  },
];

export const LibrariesAndFrameworks = [
  {
    id: 1,
    skill_name: "NextJs",
    des: "React Framework",
    Image: "/skills/next.png",
    width: 70,
    height: 70,
  },
  {
    id: 2,
    skill_name: "ReactJs", 
    des: "JavaScript Library",
    Image: "/skills/react.png",
    width: 75,
    height: 75,
  },
  {
    id: 3,
    skill_name: "Redux",
    des: "State Managing Library",
    Image: "/skills/redux.png",
    width: 65,
    height: 65,
  },
  {
    id: 4,
    skill_name: "React Query",
    Image: "/skills/reactquery.png",
    des: "JavaScript Library",
    width: 70,
    height: 70,
  },
  {
    id: 5,
    skill_name: "Framer Motion",
    Image: "/skills/framer.png",
    des: "Powerful Motion Library",
    width: 65,
    height: 65,
  },
  {
    id: 6,
    skill_name: "Tailwind Css",
    Image: "/skills/tailwind.png",
    des: "CSS Framework",
    width: 80,
    height: 80,
  },
  {
    id: 7,
    skill_name: "Express js",
    Image: "/skills/express.png",
    des: "NodeJs Framework",
    width: 65,
    height: 65,
  },
  {
    id: 8,
    skill_name: "NumPy",
    Image: "/skills/numpy.svg",
    des: "Scientific Computing Library",
    width: 65,
    height: 65,
  },
  {
    id: 9,
    skill_name: "Pandas",
    Image: "/skills/pandas.svg",
    des: "Data Analysis Library",
    width: 65,
    height: 65,
  },
  {
    id: 10,
    skill_name: "Flutter",
    Image: "/skills/flutter.png",
    des: "UI Framework",
    width: 65,
    height: 65,
  }
];

export const ProgrammingLanguages = [
  {
    id: 1,
    skill_name: "JavaScript",
    Image: "/skills/js.png",
    des: "Programming Language",
    width: 55,
    height: 55,
  },
  {
    id: 2,
    skill_name: "Type Script",
    des: "Typed Programming Language",
    Image: "/skills/ts.png",
    width: 60,
    height: 60,
  },
  {
    id: 3,
    skill_name: "C",
    Image: "/skills/c.png",
    des: "Programming Language",
    width: 70,
    height: 70,
  },
  {
    id: 4,
    skill_name: "C++",
    Image: "/skills/c++.png",
    des: "Programming Language",
    width: 70,
    height: 70,
  },
  {
    id: 5,
    skill_name: "Python",
    Image: "/skills/python.png",
    des: "Programming Language",
    width: 70,
    height: 70,
  },
  {
    id: 6,
    skill_name: "Dart",
    Image: "/skills/dart.png",
    des: "Programming Language",
    width: 70,
    height: 70,
  },
  {
    id: 7,
    skill_name: "MySQL",
    Image: "/skills/mysql.png",
    des: "Database System",
    width: 70,
    height: 70,
  },
  {
    id: 8,
    skill_name: "MongoDB",
    Image: "/skills/mongodb.png",
    des: "Database System",
    width: 70,
    height: 70,
  },
  {
    id: 9,
    skill_name: "NodeJS",
    Image: "/skills/node-js.png",
    des: "Runtime Environment",
    width: 70,
    height: 70,
  },
  {
    id: 10,
    skill_name: "HTML",
    Image: "/skills/html.png",
    des: "Markup Language",
    width: 70,
    height: 70,
  },
  {
    id: 11,
    skill_name: "CSS",
    Image: "/skills/css.png",
    des: "Style Sheet Language",
    width: 70,
    height: 70,
  }
];

export const DeveloperTools = [
  {
    id: 1,
    skill_name: "Git",
    Image: "/skills/git.png",
    des: "Version Control System",
    width: 90,
    height: 90,
  },
  {
    id: 2,
    skill_name: "GitHub",
    Image: "/skills/gitwhite.png",
    des: "Code Repository Platform",
    width: 65,
    height: 65,
  },

  {
    id: 3,
    skill_name: "Vercel",
    Image: "/skills/vercel-icon.svg",
    des: "Deployment Platform",
    width: 75,
    height: 75,
  },
  {
    id: 4,
    skill_name: "Netlify",
    Image: "/skills/netlify.png",
    des: "Deployment Platform",
    width: 80,
    height: 80,
  },
  {
    id: 5,
    skill_name: "Postman",
    Image: "/skills/postman.png",
    des: "API Testing Tool",
    width: 75,
    height: 75,
  },
  {
    id: 6,
    skill_name: "VS Code",
    Image: "/skills/vscode.svg",
    des: "Code Editor",
    width: 75,
    height: 75,
  },
  {
    id: 7,
    skill_name: "Android Studio",
    Image: "/skills/as-icon.svg",
    des: "IDE for Android",
    width: 75,
    height: 75,
  },
  {
    id: 8,
    skill_name: "AWS",
    Image: "/skills/aws.png",
    des: "Cloud Service",
    width: 75,
    height: 75,
  }
];
