export const SocialHandles = [
  {
    name: "GitHub",
    src: "/socials/github-icon.svg",
    link: "https://github.com/msxcodes",
  },
  {
    name: "Twitter",
    src: "/socials/x-icon.svg",
    link: "https://x.com/msxcodes",
  },
  {
    name: "LinkedIn",
    src: "/socials/linkedin-icon02.svg",
    link: "https://www.linkedin.com/in/msxcodes/",
  },
  {
    name: "Instagram",
    src: "/socials/insta-icon02.svg",
    link: "https://www.instagram.com/msxcodes",
  },
];

export const Frontend_skill = [
  {
    id: 1,
    skill_name: "NextJs",
    des: "React Framework",
    Image: "/skills/next.png",
    width: 70,
    height: 70,
  },
  {
    id: 2,
    skill_name: "ReactJs",
    des: "JavaScript Library",
    Image: "/skills/react.png",
    width: 75,
    height: 75,
  },
  {
    id: 3,
    skill_name: "Redux",
    des: "State Managing Library",
    Image: "/skills/redux.png",
    width: 65,
    height: 65,
  },
  {
    id: 4,
    skill_name: "Type Script",
    des: "Strongly Typed Programming Language",
    Image: "/skills/ts.png",
    width: 60,
    height: 60,
  },
  {
    id: 5,
    skill_name: "React Query",
    Image: "/skills/reactquery.png",
    des: "JavaScript Library",
    width: 70,
    height: 70,
  },
  {
    id: 6,
    skill_name: "Framer Motion",
    Image: "/skills/framer.png",
    des: "Powerful Motion Library",
    width: 65,
    height: 65,
  },
  {
    id: 7,
    skill_name: "Tailwind Css",
    Image: "/skills/tailwind.png",
    des: "CSS Framework",
    width: 80,
    height: 80,
  },

  {
    id: 8,
    skill_name: "JavaScript",
    Image: "/skills/js.png",
    des: "Programming Language",
    width: 55,
    height: 55,
  },
  {
    id: 9,
    skill_name: "CSS",
    Image: "/skills/css.png",
    des: "Cascading Style Sheets",
    width: 80,
    height: 80,
  },
  {
    id: 10,
    skill_name: "Html5",
    Image: "/skills/html.png",
    des: "Hyper Text Markup Language",
    width: 70,
    height: 70,
  },
];
export const Frontend_skillCard = [
  {
    id: 1,
    skill_name: "NextJs",
    des: "React Framework",
    Image: "/skills/next.png",
    width: 70,
    height: 70,
  },
  {
    id: 2,
    skill_name: "ReactJs",
    des: "JavaScript Library",
    Image: "/skills/react.png",
    width: 75,
    height: 75,
  },
  {
    id: 3,
    skill_name: "Redux",
    des: "State Managing Library",
    Image: "/skills/redux.png",
    width: 65,
    height: 65,
  },
  {
    id: 4,
    skill_name: "Type Script",
    des: "Programming Language",
    Image: "/skills/ts.png",
    width: 60,
    height: 60,
  },
  {
    id: 5,
    skill_name: "React Query",
    Image: "/skills/reactquery.png",
    des: "JavaScript Library",
    width: 70,
    height: 70,
  },
  {
    id: 6,
    skill_name: "Framer Motion",
    Image: "/skills/framer.png",
    des: "",
    width: 65,
    height: 65,
  },
  {
    id: 7,
    skill_name: "Tailwind Css",
    Image: "/skills/tailwind.png",
    des: "CSS Framework",
    width: 80,
    height: 80,
  },

  {
    id: 8,
    skill_name: "JavaScript",
    Image: "/skills/js.png",
    designation: "Programming Language",
    width: 55,
    height: 55,
  },
  {
    id: 9,
    skill_name: "CSS",
    Image: "/skills/css.png",
    des: "Cascading Style Sheets",
    width: 80,
    height: 80,
  },
  {
    id: 10,
    skill_name: "Html5",
    Image: "/skills/html.png",
    des: "Hyper Text Markup Language",
    width: 70,
    height: 70,
  },
];

export const Backend_skillCard = [
  {
    id: 1,
    skill_name: "NodeJs",
    Image: "/skills/node-js.png",
    des: "",
    width: 70,
    height: 70,
  },
  {
    id: 2,
    skill_name: "Express js",
    Image: "/skills/express.png",
    des: "",
    width: 65,
    height: 65,
  },
  {
    id: 3,
    skill_name: "MongoDB",
    Image: "/skills/mongodb.png",
    des: "",
    width: 35,
    height: 35,
  },
  {
    id: 4,
    skill_name: "My SQL",
    Image: "/skills/mysql.png",
    des: "",
    width: 65,
    height: 65,
  },
  {
    id: 5,
    skill_name: "Git",
    Image: "/skills/git.png",
    width: 90,
    height: 90,
  },
  {
    id: 6,
    skill_name: "GitHub",
    Image: "/skills/gitwhite.png",
    width: 65,
    height: 65,
  },
  {
    id: 7,
    skill_name: "Vercel",
    Image: "/skills/vercel-icon.svg",
    width: 75,
    height: 75,
  },
  {
    id: 8,
    skill_name: "Netlify",
    Image: "/skills/netlify.png",
    width: 80,
    height: 80,
  },
  {
    id: 9,
    skill_name: "Postman",
    Image: "/skills/postman.png",
    width: 75,
    height: 75,
  },
  {
    id: 10,
    skill_name: "Vs Code",
    Image: "/skills/vscode.svg",
    width: 75,
    height: 75,
  },
  {
    id: 11,
    skill_name: "Android Studio",
    Image: "/skills/as-icon.svg",
    width: 75,
    height: 75,
  },
];
export const Backend_skill = [
  {
    id: 1,
    skill_name: "NodeJs",
    Image: "/skills/node-js.png",
    des: "Runtime Environment",
    width: 70,
    height: 70,
  },
  {
    id: 2,
    skill_name: "Express js",
    Image: "/skills/express.png",
    des: "NodeJs Framework",
    width: 65,
    height: 65,
  },
  {
    id: 3,
    skill_name: "MongoDB",
    Image: "/skills/mongodb.png",
    des: "DBMS",
    width: 35,
    height: 35,
  },
  {
    id: 4,
    skill_name: "My SQL",
    Image: "/skills/mysql.png",
    des: "DBMS",
    width: 65,
    height: 65,
  },
];
export const Languages = [
  {
    id: 1,
    skill_name: "C",
    Image: "/skills/c.png",
    des: "Programing Language",
    width: 70,
    height: 70,
  },
  {
    id: 2,
    skill_name: "C++",
    Image: "/skills/c++.png",
    des: "Programing Language",
    width: 70,
    height: 70,
  },
];

export const Other_skill = [
  {
    id: 1,
    skill_name: "Git",
    Image: "/skills/git.png",
    des: "Version Control System",
    width: 90,
    height: 90,
  },
  {
    id: 2,
    skill_name: "GitHub",
    Image: "/skills/gitwhite.png",
    des: "Tool",
    width: 65,
    height: 65,
  },
  {
    id: 3,
    skill_name: "Vercel",
    Image: "/skills/vercel-icon.svg",
    des: "Cloud Platform",
    width: 75,
    height: 75,
  },
  {
    id: 4,
    skill_name: "Netlify",
    Image: "/skills/netlify.png",
    des: "Cloud Platform",
    width: 80,
    height: 80,
  },
  {
    id: 5,
    skill_name: "Postman",
    Image: "/skills/postman.png",
    des: "API Platform",
    width: 75,
    height: 75,
  },
  {
    id: 6,
    skill_name: "Vs Code",
    Image: "/skills/vscode.svg",
    des: "Code Editor",
    width: 75,
    height: 75,
  },
  {
    id: 7,
    skill_name: "Android Studio",
    Image: "/skills/as-icon.svg",
    des: "Code Editor",
    width: 75,
    height: 75,
  },
];
